name: Android CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
jobs:

  buildTest:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download Dependencies
        run: bash ./gradlew dependencies
      - name: Build with Gradle
        run: bash ./gradlew check assemble assembleAndroidTest --stacktrace

